server:
  port: 8189
jwt:
  secret: jwt-secret-key
  lifetime: 864000000
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        order_updates: true
        show_sql: true
        transaction:
          jta:
            platform: enable
        connection:
          isolation: serializable
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=lab4
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
